spring.application.name=qa-order-service

spring.datasource.url=jdbc:postgresql://localhost:5432/ordersdb
spring.datasource.username=orders_user
spring.datasource.password=orders_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
